version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - yum install gtk3
      - npm run cy:parallel
  post_build:
    commands:
      - aws s3 sync allure-report s3://reporte-de-pruebas-cypress/
      - aws s3 cp --recursive --acl public-read s3://reporte-de-pruebas-cypress/ s3://reporte-de-pruebas-cypress/ --metadata-directive REPLACE
      - echo "The HTML report can be found her <https://reporte-de-pruebas-cypress.s3.eu-north-1.amazonaws.com/index.html>"
